name: cake_example
description: The lightweight, explicit testing framework for Dart.
version: 1.0.0
repository: https://github.com/Polyhedra-Studio/Cake-Dart.git
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  http: ^0.13.0

dev_dependencies:
  cake:
    path: ../
  polyhedra_lint:
    version: ^1.0.4