name: cake
description: The lightweight, explicit testing framework for Dart.
version: 5.1.0
repository: https://github.com/Polyhedra-Studio/Cake.git

environment:
  sdk: '>=2.17.0 <4.0.0'

dev_dependencies:
  polyhedra_lint:
    version: ^1.0.4