name: cake
description: The tiniest little unit tester
version: 1.0.0
repository: http://butterfree.lan:30120/dart/cake
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
