name: cake
description: The tiniest little unit tester
version: 1.1.1
repository: http://butterfree.lan:30120/#/dart/cake
publish_to: http://butterfree.lan:30117

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
