name: cake
description: The tiniest little unit tester
version: 5.0.1
repository: http://butterfree.lan:30120/dart/cake
publish_to: http://butterfree.lan:30117

environment:
  sdk: '>=2.17.0 <4.0.0'

dev_dependencies:
  polyhedra_lint:
    version: ^1.0.1
    hosted: http://butterfree.lan:30117
