name: cake
description: The lightweight, explicit testing framework - built for Dart & Flutter.
version: 6.2.0
repository: https://github.com/Polyhedra-Studio/Cake-Dart.git

environment:
  sdk: '>=2.17.0 <4.0.0'

dev_dependencies:
  polyhedra_lint:
    version: ^1.0.4